transforms:
  - parent: left_tcp
    child: left_camera
    translation: [-0.01, -0.09, 0.056]
    rotation_rpy: [0.0, 0.0, 0.0]
  - parent: left_camera
    child: left_camera_color_frame
    translation: [0.0, 0.0, 0.0]
    rotation_rpy: [0.0, 0.0, 0.0]
  - parent: left_camera
    child: left_camera_depth_frame
    translation: [0.0, 0.0, 0.0]
    rotation_rpy: [0.0, 0.0, 0.0]
