from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os


def _include(package_name: str, relative_launch: str, condition=None, launch_arguments=None):
    return IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(get_package_share_directory(package_name), "launch", relative_launch)
        ),
        condition=condition,
        launch_arguments=launch_arguments or {},
    )


def generate_launch_description():
    detector_model_default = os.path.join(
        get_package_share_directory("detector"),
        "models",
        "yolov8",
        "yolo_runs",
        "final_dataset_v1",
        "weights",
        "best.pt",
    )
    return LaunchDescription(
        [
            DeclareLaunchArgument("start_hardware", default_value="false"),
            DeclareLaunchArgument("start_detector", default_value="false"),
            DeclareLaunchArgument("start_table_surface_detector", default_value="true"),
            DeclareLaunchArgument("start_camera_bridge", default_value="false"),
            DeclareLaunchArgument("require_verified_camera_extrinsics", default_value="true"),
            DeclareLaunchArgument("allow_unverified_camera_extrinsics", default_value="false"),
            DeclareLaunchArgument("required_camera_calibration_status", default_value="verified"),
            DeclareLaunchArgument("use_mock_camera_stream", default_value="false"),
            DeclareLaunchArgument("camera_color_device", default_value="auto"),
            DeclareLaunchArgument("camera_depth_device", default_value="auto"),
            DeclareLaunchArgument("camera_depth_backend", default_value="auto"),
            DeclareLaunchArgument("camera_v4l2_depth_unit_to_mm_scale", default_value="0.125"),
            DeclareLaunchArgument("publish_fake_joint_states", default_value="false"),
            DeclareLaunchArgument("detector_executable", default_value="detector_pt_node.py"),
            DeclareLaunchArgument("detector_model_path", default_value=detector_model_default),
            DeclareLaunchArgument("detector_image_topic", default_value="/camera/color/image_raw"),
            DeclareLaunchArgument("detector_allowed_class_ids", default_value="[0,1,2,3,4,5]"),
            DeclareLaunchArgument("depth_require_depth_aligned_detections", default_value="false"),
            DeclareLaunchArgument("depth_require_camera_info_depth_frame", default_value="true"),
            DeclareLaunchArgument("depth_expected_detection_frame", default_value="left_camera_color_frame"),
            DeclareLaunchArgument("ball_require_depth_aligned_detections", default_value="false"),
            DeclareLaunchArgument("ball_require_camera_info_depth_frame", default_value="true"),
            DeclareLaunchArgument("ball_expected_detection_frame", default_value="left_camera_color_frame"),
            DeclareLaunchArgument("table_timer_hz", default_value="2.0"),
            DeclareLaunchArgument("table_min_depth_mm", default_value="60.0"),
            DeclareLaunchArgument("table_max_depth_mm", default_value="3000.0"),
            DeclareLaunchArgument("table_plane_threshold_mm", default_value="22.0"),
            DeclareLaunchArgument("table_color_distance_threshold", default_value="34.0"),
            DeclareLaunchArgument("table_min_inlier_ratio", default_value="0.45"),
            DeclareLaunchArgument("table_min_inliers", default_value="500"),
            DeclareLaunchArgument("pick_assist_rgb_overlay_topic", default_value="/perception/pick_assist/rgb_overlay"),
            DeclareLaunchArgument("left_robot_ip", default_value="192.168.58.2"),
            DeclareLaunchArgument("right_robot_ip", default_value="192.168.58.3"),
            DeclareLaunchArgument("left_base_x", default_value="0"),
            DeclareLaunchArgument("left_base_y", default_value="0.35"),
            DeclareLaunchArgument("left_base_z", default_value="0"),
            DeclareLaunchArgument("left_base_roll", default_value="0"),
            DeclareLaunchArgument("left_base_pitch", default_value="0"),
            DeclareLaunchArgument("left_base_yaw", default_value="0"),
            DeclareLaunchArgument("right_base_x", default_value="0"),
            DeclareLaunchArgument("right_base_y", default_value="-0.35"),
            DeclareLaunchArgument("right_base_z", default_value="0"),
            DeclareLaunchArgument("right_base_roll", default_value="0"),
            DeclareLaunchArgument("right_base_pitch", default_value="0"),
            DeclareLaunchArgument("right_base_yaw", default_value="3.141592653589793"),
            DeclareLaunchArgument("left_robot_port", default_value="8080"),
            DeclareLaunchArgument("right_robot_port", default_value="8080"),
            DeclareLaunchArgument("robot_state_query_interval", default_value="0.05"),
            DeclareLaunchArgument(
                "left_gripper_port",
                default_value="/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_A7BIb114J19-if00-port0",
            ),
            DeclareLaunchArgument(
                "right_gripper_port",
                default_value="/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_A_COb114J19-if00-port0",
            ),
            DeclareLaunchArgument("start_console_web", default_value="false"),
            DeclareLaunchArgument("profile", default_value="test"),
            _include(
                "dualarm_bringup",
                "competition_core.launch.py",
                launch_arguments={
                    "start_hardware": LaunchConfiguration("start_hardware"),
                    "start_detector": LaunchConfiguration("start_detector"),
                    "start_table_surface_detector": LaunchConfiguration("start_table_surface_detector"),
                    "start_camera_bridge": LaunchConfiguration("start_camera_bridge"),
                    "require_verified_camera_extrinsics": LaunchConfiguration("require_verified_camera_extrinsics"),
                    "allow_unverified_camera_extrinsics": LaunchConfiguration("allow_unverified_camera_extrinsics"),
                    "required_camera_calibration_status": LaunchConfiguration("required_camera_calibration_status"),
                    "use_mock_camera_stream": LaunchConfiguration("use_mock_camera_stream"),
                    "camera_color_device": LaunchConfiguration("camera_color_device"),
                    "camera_depth_device": LaunchConfiguration("camera_depth_device"),
                    "camera_depth_backend": LaunchConfiguration("camera_depth_backend"),
                    "camera_v4l2_depth_unit_to_mm_scale": LaunchConfiguration("camera_v4l2_depth_unit_to_mm_scale"),
                    "publish_fake_joint_states": LaunchConfiguration("publish_fake_joint_states"),
                    "detector_executable": LaunchConfiguration("detector_executable"),
                    "detector_model_path": LaunchConfiguration("detector_model_path"),
                    "detector_image_topic": LaunchConfiguration("detector_image_topic"),
                    "detector_allowed_class_ids": LaunchConfiguration("detector_allowed_class_ids"),
                    "depth_require_depth_aligned_detections": LaunchConfiguration("depth_require_depth_aligned_detections"),
                    "depth_require_camera_info_depth_frame": LaunchConfiguration("depth_require_camera_info_depth_frame"),
                    "depth_expected_detection_frame": LaunchConfiguration("depth_expected_detection_frame"),
                    "ball_require_depth_aligned_detections": LaunchConfiguration("ball_require_depth_aligned_detections"),
                    "ball_require_camera_info_depth_frame": LaunchConfiguration("ball_require_camera_info_depth_frame"),
                    "ball_expected_detection_frame": LaunchConfiguration("ball_expected_detection_frame"),
                    "table_timer_hz": LaunchConfiguration("table_timer_hz"),
                    "table_min_depth_mm": LaunchConfiguration("table_min_depth_mm"),
                    "table_max_depth_mm": LaunchConfiguration("table_max_depth_mm"),
                    "table_plane_threshold_mm": LaunchConfiguration("table_plane_threshold_mm"),
                    "table_color_distance_threshold": LaunchConfiguration("table_color_distance_threshold"),
                    "table_min_inlier_ratio": LaunchConfiguration("table_min_inlier_ratio"),
                    "table_min_inliers": LaunchConfiguration("table_min_inliers"),
                    "pick_assist_rgb_overlay_topic": LaunchConfiguration("pick_assist_rgb_overlay_topic"),
                    "left_robot_ip": LaunchConfiguration("left_robot_ip"),
                    "right_robot_ip": LaunchConfiguration("right_robot_ip"),
                    "left_base_x": LaunchConfiguration("left_base_x"),
                    "left_base_y": LaunchConfiguration("left_base_y"),
                    "left_base_z": LaunchConfiguration("left_base_z"),
                    "left_base_roll": LaunchConfiguration("left_base_roll"),
                    "left_base_pitch": LaunchConfiguration("left_base_pitch"),
                    "left_base_yaw": LaunchConfiguration("left_base_yaw"),
                    "right_base_x": LaunchConfiguration("right_base_x"),
                    "right_base_y": LaunchConfiguration("right_base_y"),
                    "right_base_z": LaunchConfiguration("right_base_z"),
                    "right_base_roll": LaunchConfiguration("right_base_roll"),
                    "right_base_pitch": LaunchConfiguration("right_base_pitch"),
                    "right_base_yaw": LaunchConfiguration("right_base_yaw"),
                    "left_robot_port": LaunchConfiguration("left_robot_port"),
                    "right_robot_port": LaunchConfiguration("right_robot_port"),
                    "robot_state_query_interval": LaunchConfiguration("robot_state_query_interval"),
                    "left_gripper_port": LaunchConfiguration("left_gripper_port"),
                    "right_gripper_port": LaunchConfiguration("right_gripper_port"),
                }.items(),
            ),
            Node(
                package="competition_console_api",
                executable="competition_console_api_node.py",
                name="competition_console_api",
                output="screen",
                parameters=[{"profile": LaunchConfiguration("profile")}],
            ),
            Node(
                package="competition_console_api",
                executable="competition_console_static_server.py",
                name="competition_console_web",
                condition=IfCondition(LaunchConfiguration("start_console_web")),
                output="screen",
            ),
        ]
    )
