frapp.factory('colorMap', function () {
    var colorMap = {};

    colorMap = {
        'Number': '#00d0fa',
        'String': '#ed1a95',
        'Boolean': '#f30909',
        'Array' : '#ccff33', 
        'SelectPoint' : 'red', 
        'SelectOffsetType' : 'red', 
        'SelectPointSeam' : 'red', 
        'SelectSegmentMode"' : 'red', 
        'SelectWeld' : 'red', 
        'SelectTplate' : 'red', 
        'SelectWire' : 'red', 
        'SelectWork' : 'red', 
        'SelectTool' : 'red', 
        'SelectMove' : 'red', 
        'SelectOffset' : 'red',
        'SelectOffsetLaser' : 'red',
        'SelectDirection' : 'red',
        'SelectWeave' : 'red',
        'SelectTpd' : 'red',
        'SelectTraj' : 'red',
        'SelectTrajmode' : 'red',
        'SelectSplinemode' : 'red',
        'SelectNspiral' : 'red',
    	'SelectBlock' : 'red', 
        'SelectSmooth' : 'red', 
        'SelectPort' : 'red',
        'SelectGripper' : 'red',
        'SelectAxismove' : 'red',
        'SelectAxisnumber' : 'red',
        'SelectZero' : 'red',
        'SelectServo' : 'red',
        'SelectServomode' : 'red',
        'SelectServoenable' : 'red',
        'SelectIO' : 'red',
        'SelectWeldId' : 'red',
        'SelectDO' : 'red',
        'SelectFuncMode' : 'red',
        'SelectWeaveMode' : 'red',
        'SelectRounding' : 'red',
        'SelectProtocol' : 'red',
        'SelectFuncType' : 'red',
        'SelectSearch' : 'red',
        'SelectTraceIs' : 'red',
        'SelectTraceAxis' : 'red',
        'SelectTraceReference' : 'red',
        'SelectTechPlate' : 'red',
        'SelectTechMotion' : 'red',
        'SelectInfPoint' : 'red',
        'SelectWirePos' : 'red',
        'SelectWireSerachBack' : 'red',
        'SelectWireSerachMode' : 'red',
        'SelectWireSearchResPoint' : 'red',
        'SelectLockDirection' : 'red',
        'SelectPointTable' : 'red',
        'SelectWireSearchRefPoint' : 'red',
        'SelectCalcMethod1' : 'red',
        'SelectCalcMethod2' : 'red',
        'SelectCalcMethod3' : 'red',
        'SelectCalcMethod4' : 'red',
        'SelectCalcMethod5' : 'red',
        'SelectModbusRegWrite' : 'red',
        'SelectModbusRegRead' : 'red',
        'SelectModbusType' : 'red',
        'SelectModbus' : 'red',
        'SelectFTControlilc' : 'red',
        'SelectFTControlAdj' : 'red',
        'SelectFTControlFilter' : 'red',
        'SelectFTControlPA' : 'red',
        'SelectSensorTool' : 'red',
        'SelectFTRotor' : 'red',
        'SelectFTSurfaceAxis' : 'red',
        'SelectFTSurfaceDirection' : 'red',
        'SelectFTReference' : 'red',
        'SelectSmoothType' : 'red',
        'SelectCollisionLevel' : 'red',
        'SelectDofile' : 'red',
        'SelectCollideMode' : 'red',
        'SelectPause' : 'red',
        'SelectlayerId' : 'red',
        'SelectConnection' : 'red',
        'SelectWhetherMotion' : 'red',
        'SelectWobjToolCoord' : 'red',
        'SelectToolCoord' : 'red',
        'SelectVirAinData' : 'red',
        'SelectVirDinData' : 'red',
        'SelectAICompare' : 'red',
        'SelectAIPort' : 'red',
        'SelectAOPort' : 'red',
        'SelectDIPort' : 'red',
        'SelectWhether' : 'red',
        'SelectRobotMode' : 'red',
        'SelectOutputMode' : 'red',
        'Data': '#ff7900',
        'MainLabel': '#ffffff',
        'MainLabelBox': '#3282b8',
        // 'MainLabelBox': '#7209b7',
        // 'MainBox': '#3c415c',
        // 'MainBox': '#413D65', 
        'MainBoxGradient': {
            'start': '#28313b',
            'end': '#485461',
        },
        'Text': '#ffffff',
        'Logic': '#7209b7',
        'Get': '#008000',
        'Math': '#ae2012',
        'Func': '#0353a4',
        'Begin': '#d8572a',
        'Print' : '#bc4749',
        'Motion' : 'rgb(91, 103, 165)',
        'Pherial' : 'rgb(153, 91, 165)',
        'Weld' : 'rgb(165, 103, 91)',
    }

    return colorMap;
})


//red: #ae2012
//green: #008000
//blue: #0353a4
//violet: #7209b7